name: Build & Test

on:
    push:
      branches: ["main"]
    pull_request:
      branches: ["main"]
  
    workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    if: "${{ !contains(github.event.head_commit.message, 'ci skip') }}"

    steps:
      - uses: actions/checkout@v3

      - name: Check deps versions
        run: |
          cmake --version
          ctest --version
          g++ --version
        
      - name: Build
        run: |
          cmake -B build/ -DCMAKE_BUILD_TYPE=Debug
          cmake --build build/ -j
      - name: Run tests
        run: |
          ctest --test-dir ./build/ --output-on-failure -T Test
      
      - name: Run CppCheck
        run: |
          bash scripts/run-cppcheck.sh
      
      - name: Run clang-tidy
        run: |
          bash scripts/run-clang-tidy.sh
