name: Development PR CI

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-test-main-pr:
    strategy:
      matrix:
        os: ["ubuntu-22.04"]
        build_type: ["Debug"]
        cc: ["gcc-10"]
        cxx: ["g++-10"]

    uses: ./.github/workflows/build-test.yml
    with:
      os: ${{ matrix.os }}
      build_type: ${{ matrix.build_type }}
      cc: ${{ matrix.cc }}
      cxx: ${{ matrix.cxx }}
      static_analysis: true
