name: Build & Test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      build_type:
        required: true
        type: string
      cc:
        required: true
        type: string
      cxx:
        required: true
        type: string

jobs:
  build-and-test:
    name: ${{ inputs.build_type }} Build & Test
    runs-on: ${{ inputs.os }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}

    env:
      CC: ${{ inputs.cc }}
      CXX: ${{ inputs.cxx }}

    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: sudo apt install -y cppcheck gdb

      - name: Build
        run: |
          cmake -B build/ \
            -DCMAKE_BUILD_TYPE=${{ inputs.build_type }}
          cmake --build build/ -j

      - name: Test
        run: ctest --test-dir ./build/ --output-on-failure -T Test

      - name: CppCheck
        run: bash scripts/run-cppcheck.sh

      - name: clang-tidy
        if: ${{ inputs.build_type == 'Release' }}
        run: bash scripts/run-clang-tidy.sh
